name: Build Electron App for Windows

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Electron Packager
        run: npm install --save-dev electron-packager

      - name: Build Vite app
        run: npm run build

      - name: Package Electron app for Windows
        run: npx electron-packager . SEAdminApp --platform=win32 --arch=x64 --out=release-build --overwrite --icon=public/SE_logo_2.ico --prune=true --ignore="^/release-build$|^/src$|^/bin$|^/lib$|^/electron-package.json$|^/serve_spa.py$|^/ELECTRON_README.txt$"

      - name: Upload Windows .exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SEAdminApp-win32-x64
          path: release-build/SEAdminApp-win32-x64/
